name: share_example
description: Demonstrates how to use the share plugin.

dependencies:
  flutter:
    sdk: flutter
  share:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"
